name: TESTING 1234

on:
  workflow_dispatch:
    inputs:
      params:
        type: string
        required: true
        description: json
        default: false
jobs:

################
# ENRICH
################
  matrix-zip4:
    name: Unzip and Matrix Zip4 files
    runs-on: [self-hosted, Linux, x64, lob-runner]
    strategy:
      matrix:
        service: ${{ fromJSON(inputs.params) }}

    outputs:
      should_run: steps.matrix-zip4.outputs.should_run
    steps:
      - name: Shortcut if already run
        id: should-run
        run: |
          echo "${{ matrix.zip4-file }}" >> $GITHUB_OUTPUT
