name: TESTING 1234

on:
  workflow_dispatch:
    inputs:
      params:
        type: boolean
        required: true
        description: json
        default: false
jobs:

################
# ENRICH
################
  matrix-zip4:
    name: Unzip and Matrix Zip4 files
    runs-on: [self-hosted, Linux, x64, lob-runner]
    env:
      ForceIngestion: ${{ inputs.force_ingestion }}
      EffectiveDate: ${{ inputs.fulfilled_date }}
      ImageOS: ubuntu20
    outputs:
      zip4_files: steps.matrix-zip4.outputs.zip4_files
    steps:
      - name: Enrich ZIP4 and write to file
        run: |
          RESULT='["DEMO.txt"]'
          echo 'zip4_files=${RESULT}' >> $GITHUB_OUTPUT

  enrich-zip4:
    name: Enrich Zip4
    runs-on: [self-hosted, Linux, x64, lob-runner]
    needs: [matrix-zip4]
    strategy:
      matrix:
        zip4-file: ${{ fromJSON(needs.matrix-zip4.outputs.zip4_files) }}
    env:
      ImageOS: ubuntu20
    steps:
      - name: PRINT
        run: |
          echo '>> ${matrix.zip4-file}'
